#!/usr/bin/env bash

# Wait for services
sleep 5

# Prevent showing "Restore Pages" dialog in chromium
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' "$HOME/.config/chromium/Default/Preferences"
sed -i 's/"exit_type":"Crashed"/"exit_type":"Normal"/' "$HOME/.config/chromium/Default/Preferences"
