#!/usr/bin/env bash

# Wait for services (internet, chromium, etc)
sleep 10

# Load nvm environment
source "$HOME/.config/nvm/nvm.sh"

STOCK_TICKER_HOME="$HOME/stock-ticker"

# Disable power saving and screen savers
xset s noblank
xset s off
xset -dpms

# Update
cd "$STOCK_TICKER_HOME"
git pull
yarn

# Start
yarn prod
