#!/usr/bin/env bash

source "$HOME/.config/nvm/nvm.sh"

STOCK_TICKER_HOME="$HOME/stock-ticker"
CHROMIUM_PORT=9123

# Disable power saving and screen savers
xset s noblank
xset s off
xset -dpms

# Update
cd "$STOCK_TICKER_HOME"
git pull
yarn

# Start
sleep 10
yarn prod
