#!/usr/bin/env bash

# Wait for services
sleep 15

# Load nvm environment
source "$HOME/.config/nvm/nvm.sh"

STOCK_TICKER_HOME="$HOME/stock-ticker"

# Disable power saving and screen savers
xset s noblank
xset s off
xset -dpms

# Update
cd "$STOCK_TICKER_HOME"
git pull
NODE_ENV=production yarn install --prod --ignore-scripts

# Start
yarn prod
