#!/usr/bin/env bash

STOCK_TICKER_HOME="$HOME/stock-ticker"

# Disable power saving and screen savers
xset s noblank
xset s off
xset -dpms

# Update
cd "$STOCK_TICKER_HOME"
git pull
NODE_ENV=production yarn start
